import type { Metadata } from "next";

import '../assets/sass/main.scss';
import App from "./App";
import { TratteggioProvider } from "@/contexts/TratteggioContext";
import { ArchiveProvider } from "@/contexts/ArchiveContext";

export const metadata: Metadata = {
  title: "Blauer Schnipsel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body>
        <ArchiveProvider>
          <TratteggioProvider>
            <App>{children}</App>
          </TratteggioProvider>
        </ArchiveProvider>
      </body>
    </html>
  );
}
